-- Migration 003
-- Création de la table des candidatures ASD

create table public.inscriptions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nom text,
  email text,
  telephone text,
  formation text,
  message text,
  statut text default 'Nouveau',

  constraint inscriptions_pkey primary key (id)
);