-- Migration 006
-- Création du catalogue des formations ASD

create table public.formations (
  id bigint generated by default as identity primary key,

  nom text not null unique,
  slug text not null unique,

  description text,
  public_cible text,
  prerequis text,

  duree_semaines integer not null,
  heures_total integer,

  is_active boolean not null default true,
  ordre integer not null,

  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint formations_duree_semaines_check
    check (duree_semaines > 0),

  constraint formations_heures_total_check
    check (heures_total is null or heures_total > 0),

  constraint formations_ordre_check
    check (ordre > 0)
);